name: annai_store
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specif
dependencies:
  barcode: ^2.1.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.0
  encrypt: ^5.0.1
  environments:
    git:
      url: https://github.com/AgnelSelvan/custom_packages_flutter.git
      path: environments
  equatable: ^2.0.5
  excel: ^2.1.0
  file_picker: null
  filepicker_windows: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_p2p_plus: ^1.0.2
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^8.0.0
  flutter_typeahead: ^3.1.3
  function_tree: ^0.9.0
  get: ^4.1.4
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.3
  intl: null
  json_annotation: ^4.0.1
  localstorage: ^4.0.0+1
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1
  number_to_words: ^1.0.0
  path_provider: ^2.0.2
  pdf: ^3.4.2
  printing: ^5.11.0
  screenshot: ^2.1.0
  syncfusion_flutter_barcodes: null
  syncfusion_flutter_charts: null
  syncfusion_flutter_datepicker: null
  syncfusion_flutter_pdfviewer: null
  tcp_socket_connection: ^0.3.1
  uuid: ^3.0.4
  validators:
    git:
      url: https://github.com/AgnelSelvan/custom_packages_flutter.git
      path: validators
  window_manager: ^0.3.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  lint: ^2.1.2
  msix: ^3.6.2

dependency_overrides:
  watcher: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  # - assets/pdf/
  # - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# msix_config:
#   display_name: Annai Store
#   publisher_display_name: Agnel Selvan
#   identity_name: com.software.annai_store
#   msix_version: 1.0.0.0
#   logo_path: C:\Users\Agnel.Selvan\OneDrive - Aurum\Documents\some\assets\images\annai_store.png
#   capabilities:
#   debug: false
#   output_path: C:\Users\Agnel.Selvan\OneDrive - Aurum\Desktop\
#   output_name: testing
#   build_windows: true
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/annai_traders.png"
    icon_size: 48

# flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml
